---
##
# Red     = #F44
# Orange  = #F71
# Green   = #0A5
# Blue    = #05B
# Cyan    = #0AF
# Purple  = #A4F
##
GlobalConfig:
  GameNamePrefix: "<#0AF>[CYAN]</> "
  GameNameSuffix: ""
  MessageOfTheDayHeader: ""
  MessageOfTheDayFooter: |
    If you have any issues or suggestions, reach out on discord <#67F>CyanAwesome#7386</>
Defaults:
  GameName: "Change Me"
  MessageOfTheDay: ""
  ReportToMassgate: true
  Password: null
  AdminPassword: null
  AdminPort: null
  CustomMapPath: maps
  ModName: null
  RandomMapCycle: true
  NonLinearDominationDisabled: false
  BannerUrl: null
  Ranked: false
  Tournament: false
  ClanMatch: false
  QueryPort: 48000
  GamePortRangeStart: 48000
  MinPlayersPerTeam: 1
  MaxPlayersPerTeam: 4
  StayOnTeam: false
  UseFireWallSettings: false
  PrivateIP: null
  RestartInterval: 1
  MatchMode: false
  FewPlayerMode: false
  MaxTeamImbalanceCount: 2
  AutoBalanceTeams: true
  AutoBalanceStartDelay: 45
  TimeLimitMultiplier: 1.0
  UseCDKey: false
  RankBalanceTeams: false
  AllowSpectating: true
  AllowFreeSpectating: true
  AllowSpectatorVoting: true
  NumAllowedPlayersPerRole: 4
  MaxNumAllowedTeamChanges: -1
  BanTime: 90
  MaxAllowedIdleTime: 0
  ChatTimeSpan: 20
  BotMode: 0
  AutoEvenPlayersPerTeam: 6
  AutoEvenBotDifficulty: 1
  MaxChatMessages: 5
  ChatSpamMuteTime: 120
  RequestTimeSpan: 20
  MaxRequests: 5
  RequestSpamMuteTime: 30
  FriendlyFireLimit: 50
  PvsBBotTeam: 1
  PvsBNumBots: 4
  PvsBBotDifficulty: 1
  MapCycle:
    - do_Hometown
    - do_Xmas
    - do_Seaside
    - do_SpaceNeedle
    - as_Dome
    - as_Bridge
    - do_Island
    - do_Liberty
    - do_Farmland
    - tw_Wasteland
    - do_Riverbed
    - tw_Highway
    - do_Silo
    - as_AirBase
    - do_Ruins
    - as_Hillside
    - do_Riviera
    - tw_Radar
    - do_Powerplant
    - do_Quarry
    - as_Typhoon
    - do_Mauer
    - do_Fjord
    - do_Studio
    - do_Canal
    - do_Apocalypse
    - do_Tequila
    # # New Maps
    # - as_Ozzault
    # - do_Airport
    # - do_AmazingIsland
    # - do_BeachAssault
    # - do_Coal
    # - do_Heligoland
    # - do_Marseille
    # - do_Midway
    # - do_Oil
    # - do_Ozz
    # - do_Paradise
    # - do_Valley
    # - do_Wake
    # - tw_Arizona
    # - tw_bocage
    # - virginia
  BanList: []
Instances:
  Odin:
    GameName: "<#8F9>Domination</> :: Odin"
    MessageOfTheDay: ""
    MinPlayersPerTeam: 1
    MaxPlayersPerTeam: 8
    MapCycle:
      - do_Hometown
      - do_Xmas
      - do_Seaside
      - do_SpaceNeedle
      - do_Island
      - do_Liberty
      - do_Farmland
      - do_Riverbed
      - do_Silo
      - do_Ruins
      - do_Riviera
      - do_Powerplant
      - do_Quarry
      - do_Mauer
      - do_Fjord
      - do_Studio
      - do_Canal
      - do_Apocalypse
      - do_Tequila
  Thor:
    GameName: "<#8F9>Domination | MM</> :: Thor"
    MessageOfTheDay: ""
    MinPlayersPerTeam: 1
    MaxPlayersPerTeam: 5
    MatchMode: true
    StayOnTeam: true
    MapCycle:
      - do_Hometown
      - do_Xmas
      - do_Seaside
      - do_SpaceNeedle
      - do_Island
      - do_Liberty
      - do_Farmland
      - do_Riverbed
      - do_Silo
      - do_Ruins
      - do_Riviera
      - do_Powerplant
      - do_Quarry
      - do_Mauer
      - do_Fjord
      - do_Studio
      - do_Canal
      - do_Apocalypse
      - do_Tequila
  Heimdall:
    GameName: "<#8F9>Seaside | 1v1</> :: Heimdall"
    MessageOfTheDay: ""
    MinPlayersPerTeam: 1
    MaxPlayersPerTeam: 1
    BotMode: 1
    AutoEvenPlayersPerTeam: 1
    AutoEvenBotDifficulty: 1
    AdminPort: 3000
    MapCycle:
      - do_Seaside
  Loki:
    GameName: "<#8F9>Domination | Bots</> :: Loki"
    MinPlayersPerTeam: 1
    MaxPlayersPerTeam: 8
    BotMode: 1
    AutoEvenPlayersPerTeam: 4
    AutoEvenBotDifficulty: 1
    MapCycle:
      - do_Hometown
      - do_Xmas
      - do_Seaside
      - do_SpaceNeedle
      - do_Island
      - do_Liberty
      - do_Farmland
      - do_Riverbed
      - do_Silo
      - do_Ruins
      - do_Riviera
      - do_Powerplant
      - do_Quarry
      - do_Mauer
      - do_Fjord
      - do_Studio
      - do_Canal
      - do_Apocalypse
      - do_Tequila
  Meili:
    GameName: "<#8F9>Casual | Bots</> :: Meili"
    MinPlayersPerTeam: 1
    MaxPlayersPerTeam: 8
    BotMode: 1
    AutoEvenPlayersPerTeam: 4
    AutoEvenBotDifficulty: 0
    MapCycle:
      - do_Hometown
      - do_Xmas
      - do_Seaside
      - do_SpaceNeedle
      - as_Dome
      - as_Bridge
      - do_Island
      - do_Liberty
      - do_Farmland
      - tw_Wasteland
      - do_Riverbed
      - tw_Highway
      - do_Silo
      - as_AirBase
      - do_Ruins
      - as_Hillside
      - do_Riviera
      - tw_Radar
      - do_Powerplant
      - do_Quarry
      - as_Typhoon
      - do_Mauer
      - do_Fjord
      - do_Studio
      - do_Canal
      - do_Apocalypse
      - do_Tequila
